eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true
server:
  port: 8767

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 360000
        timeout:
          enabled: true
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50

spring:
  application:
    name: eshop-datalink-service
  cache:
    type: ehcache

    ehcache:
      config: classpath:ehcache.xml
  kafka:
    consumer:
      group-id: test-consumer-group
    bootstrap-servers: m1:9092,m2:9092,m3:9092